Styled tables branch
JosephDClark97/Crypto-Book pull request #5
Opened 2022-08-09 16:42 UTC by JosephDClark97

Created all of the styled.divs for main page table, as well as set up the main page table.

2022-08-09 20:08 UTC, yoloOnTheBattlefield requested changes

2022-08-09 20:08 UTC, yoloOnTheBattlefield commented on src/components/CoinTable/CoinTable.js
> +// import { Chart } as ChartJS;
is this code needed?

2022-08-09 20:08 UTC, yoloOnTheBattlefield commented on src/components/CoinTable/CoinTable.js
> +      fetch('https://api.coingecko.com/api/v3')
you can use async await

2022-08-09 20:08 UTC, yoloOnTheBattlefield commented on src/components/CoinTable/CoinTable.js
> +          this.setState({result: [...result.content]})
format this properly
this.setState({ result: [...result.content] })

2022-08-09 20:08 UTC, yoloOnTheBattlefield commented on src/components/CoinTable/CoinTable.js
> +      }
here as well

2022-08-09 20:08 UTC, yoloOnTheBattlefield commented on src/components/CoinTable/CoinTable.styles.js
> +color:#fff;
indent

2022-08-09 20:08 UTC, yoloOnTheBattlefield commented on src/components/ThemeChangeBtn/ThemeChangeBtn.styles.js
> +border-radius:10px;
indent

2022-08-10 23:55 UTC, JosephDClark97 commented on src/components/CoinTable/CoinTable.js
> +// import { Chart } as ChartJS;
probably not the Chart and Chart JS

2022-08-10 23:55 UTC, JosephDClark97 commented on src/components/CoinTable/CoinTable.js
> +// import { Chart } as ChartJS;
will likely need that for the actual two other charts, right ?

2022-08-10 23:58 UTC, JosephDClark97 commented on src/components/CoinTable/CoinTable.js
> +      fetch('https://api.coingecko.com/api/v3')
async componentDidMount() {
     await fetch('https://api.coingecko.com/api/v3')
        .then(result => {
          this.setState({result: [...result.content]})
        })
      }

2022-08-11 00:03 UTC, JosephDClark97 commented on src/components/CoinTable/CoinTable.js
> +          this.setState({result: [...result.content]})
is this what you mean? 
         this.setState(
            {
              result: [...result.content]
            }
            )
        })
      }

2022-08-11 00:05 UTC, JosephDClark97 commented on src/components/CoinTable/CoinTable.js
> +      }
not sure what u mean         
return ( 
        <div> 
          {
          this.state.list.map
          (
            el => 
            <div>
            {el.name}
            </div>
          )
          } 
          </div>
          )

2022-08-11 00:06 UTC, JosephDClark97 commented on src/components/CoinTable/CoinTable.styles.js
> +color:#fff;
done, indented all the rest

2022-08-11 00:06 UTC, JosephDClark97 commented on src/components/ThemeChangeBtn/ThemeChangeBtn.styles.js
> +border-radius:10px;
done

2022-08-15 03:04 UTC, merged