Landing page chart one
JosephDClark97/Crypto-Book pull request #6
Opened 2022-08-11 00:41 UTC by JosephDClark97

Styled the first Bit Coin Landing Page Chart and exported those components

2022-08-11 16:39 UTC, yoloOnTheBattlefield requested changes

2022-08-11 16:39 UTC, yoloOnTheBattlefield commented on src/components/BitChart/BitChart.styles.js
> +border-radius:1px solid #707070;
indent

2022-08-11 16:39 UTC, yoloOnTheBattlefield commented on src/components/CoinTable/CoinTable.js
> +        })
use async await

2022-08-11 16:39 UTC, yoloOnTheBattlefield commented on src/components/CoinTable/CoinTable.js
> +            </div>
indent

2022-08-13 22:34 UTC, JosephDClark97 commented on src/components/BitChart/BitChart.styles.js
> +border-radius:1px solid #707070;
completed

2022-08-13 22:35 UTC, JosephDClark97 commented on src/components/CoinTable/CoinTable.js
> +        })
how should i use it with this line ? 
what does it look like syntaxically?

2022-08-13 22:38 UTC, closed without merging